
version: '3.8'


services:
  loadbalancer:
    env_file: .env.prod
    image: nginx
    networks:
      - appstr_network
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf


  website:
    env_file: .env.prod
    image: nginx
    volumes:
      - ./website/nginx.conf:/etc/nginx/nginx.conf
      - ./website/www:/etc/www
    networks:
      - appstr_network

  cdn:
    env_file: .env.prod
    image: nginx
    networks:
      - appstr_network
    volumes:
      - ./website/images:/etc/images

  # postgres:
  #   build: postgres/

  # rest:
  #   build: rest/


networks:
  appstr_network:
    driver: bridge

