
version: '3.8'

services:
  loadbalancer:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - appstr_network


  website:
    image: nginx
    volumes:
      - ./website/nginx.conf:/etc/nginx/nginx.conf
      - ./website/www:/etc/nginx/html
    networks:
      - appstr_network

  # postgres:
  #   build: postgres/

  # rest:
  #   build: rest/


networks:
  appstr_network:
    driver: bridge

