
version: '3.8'

networks:
  appstr_network:
    driver: bridge

services:


  loadbalancer:
    env_file: .env.dev
    image: nginx
    networks: 
      - appstr_network
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf


  website:
    env_file: .env.dev
    image: nginx
    networks: 
      - appstr_network
    volumes:
      - ./website/nginx.conf:/etc/nginx/nginx.conf
      - ./website/html:/html/


  cdn:
    env_file: .env.dev
    image: nginx
    networks: 
      - appstr_network
    volumes:
      - ./cdn/nginx.conf:/etc/nginx/nginx.conf
      - ./cdn/css:/content/css
      - ./cdn/js:/content/js
      - ./cdn/images:/content/images


